config/routes.rb
Rails.application.routes.draw do
  resources :uploads do
    member do
      get :generate
    end
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tiny_url.rb
class TinyUrl < ApplicationRecord
  belongs_to :upload
end

app/models/upload.rb
class Upload < ApplicationRecord
  has_attached_file :file

  do_not_validate_attachment_file_type :file
  validates :file, attachment_presence: true

  belongs_to :user
  has_one :tiny_url

  def generate_tiny_url
    tiny_url = TinyUrl.where(upload_id: id).first
    if tiny_url
    else
      tiny_url = TinyUrl.new
      tiny_url.upload_id = id
      tiny_url.code = generate_randon_code
      tiny_url.save!
    end
  end

  def tiny_url
    return TinyUrl.where(upload_id: id).first.try(:code)
  end

  private
  def generate_randon_code
    SecureRandom.alphanumeric
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :uploads
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @uploads = current_user.uploads
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:destroy, :generate, :show]

  def new
    @upload = Upload.new
  end

  def create
    @upload = current_user.uploads.new(upload_params)
    if @upload.save
      flash[:success] = "File uploaded successfully."
      redirect_to authenticated_root_path
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @upload.destroy
    flash[:success] = "File removed successfully."
    redirect_to authenticated_root_path
  end

  def generate
    @upload.generate_tiny_url
    flash[:success] = "Tiny Url generated successfully."
    redirect_to authenticated_root_path
  end

  private
  def set_upload
    @upload = Upload.find(params[:id])
  end

  def upload_params
    params.require(:upload).permit(:title, :description, :file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/home/index.html.erb
<h1>My Uploaded Files</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">File</th>
    </tr>
  </thead>
  <tbody>
    <% @uploads.each do |upload| %>
      <tr>
        <th><%=upload.id %></th>
        <td><%=upload.title %></td>
        <td><%=upload.description %></td>
        <td><%=upload.file.url %></td>
        <td><%=link_to "Generate Tiny Url", generate_upload_path(upload) %></td>
        <td><%=link_to "Share", upload_path(upload) %></td>
        <td><%=link_to "Delete", upload_path(upload), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Upload App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">

      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "My Files", authenticated_root_path, :class => 'nav-link'  %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Add New File', new_upload_path, :class => 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link'  %>
        </li>
        <li class="nav-item active">
          <%= link_to "Login", new_user_session_path, :class => 'nav-link'  %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UploadFeature</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render partial: "layouts/navbar" %>
    <br>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/uploads/new.html.erb
<h1>Add New Upload</h1>

<%= form_for @upload, url: uploads_path, html: { multipart: true } do |form| %>
  <% if @upload.errors.any? %>
    <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <br>
  <%= form.label :description %>
  <%= form.text_field :description %>
  <br>
  <%= form.label :file %>
  <%= form.file_field :file %>
  <br>
  <%= form.submit %>
<% end %>

app/views/uploads/show.html.erb
<h1>Share Url</h1>

<P>You can share this URL: <%=unauthenticated_root_url%><%=@upload.tiny_url %></P>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>